services:
  - type: web
    name: automation-testing
    runtime: python
    pythonVersion: 3.11.0
    buildCommand: |
      apt-get update && apt-get install -y chromium chromium-driver python3-opencv
      pip install --no-cache-dir -r requirements.txt
    startCommand: python run_web_interface.py
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: CHROME_BIN
        value: /usr/bin/chromium
      - key: CHROMEDRIVER_PATH
        value: /usr/bin/chromedriver